### ISSUE TITLE
create-auctions.js not working for kovan test

### ISSUE THREAD

**Issue by jay-infocusp** [makerdao/auction-demo-keeper#65]
I can run `yarn run kovan`, but unable to run `node scripts/create-auctions.js`
It fails with error : 

Initiating Maker Service from Dai.js
web3  kovan
Current Wallet Address:  0xacd353f642fae3d50995b3e93f144ce77af9432b
Link balance  90
Ensure there is proxy address
Proxy Address:  0x7b5599f77b087A3D13CDF8d59bf7E9e35EE47805
 
--------------------------------------------------------------------
Creating risky vault
/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:4037
    var _managerContract$inte = managerContract["interface"].encodeFilterTopics('NewCdp', []),
                                                             ^

TypeError: managerContract.interface.encodeFilterTopics is not a function
    at CdpManager.getNewCdpId (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:4037:62)
    at _callee$ (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:2544:31)
    at tryCatch (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:1288:19)
    at Generator.invoke [as _invoke] (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:1508:24)
    at Generator.prototype.<computed> [as next] (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:1341:23)
    at asyncGeneratorStep (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:27:24)
    at _next (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:49:9)
    at /home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:56:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:45:12)
    at Object.create (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:2561:22)
    at CdpManager._callee5$ (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:3517:42)
    at tryCatch (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:1288:19)
    at Generator.invoke [as _invoke] (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:1508:24)
    at Generator.prototype.<computed> [as next] (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:1341:23)
    at asyncGeneratorStep (/home/jay/Desktop/Infocusp/bluerock/auction-demo-keeper/node_modules/@makerdao/dai-plugin-mcd/dist/dai-plugin-mcd.cjs.development.js:27:24)

**Comment by dharmendrakariya** [comment]
Hi @jay-infocusp How are you running on Kovan? for me its failing with below error! I am just creating wallet(keystore) and not changing anything in config! I am running nethermind (kovan) and keeper both in docker!
![image](https://user-images.githubusercontent.com/22043860/174037817-6da88613-d4df-40a6-b583-e36d8c015091.png)
